### ISSUE TITLE
Is it better to switch to use OpenAI Whisper model?

### ISSUE THREAD

**Issue by fishfree** [uhh-lt/bbb-live-subtitles#8]
OpenAI Whisper supports more languages.

**Comment by Alienmaster** [comment]
The plugin was developed for BigBlueButton 2.2.x . It wouldn't run on new versions out of the box. Also BigBlueButton now supports Closed Captions generation through Web Speech API. So in my opinion this plugin isn't necessary anymore and is no longer maintained.
